### ISSUE TITLE
Caching Quarto results make the file not renderable a second time, one way or the other

### ISSUE THREAD

**Issue by raffaem** [vincentarelbundock/modelsummary#846]
**Example 1**

Consider the following MWE:

````
---
title: "Title"
engine: knitr
execute:
  cache: true
format:
  pdf: default
---

```{r}
#| label: setup
#| output: false
library(modelsummary)
mod <- lm(mpg~cyl, data=mtcars)
```

# Section 1

```{r}
#| label: tbl-reg-results
#| output: asis
modelsummary(mod)
```
````

Open with RStudio and compile in PDF two times.

The second time you will get the following error:

```
ERROR: 
compilation failed- error
LaTeX Error: Environment tblr undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.224 \begin{tblr}
                  [         %% tabularray outer open 

see main.log for more information.
```

**Example 2**

Clean up all the temp files from the previous rendering:

```
#!/usr/bin/env bash
rm -rf *_cache *_files svg-inkscape
rm *.html *.pdf *.docx *.tex *.md *.odt *.aux *.log *.snm *.nav *.toc *.synctex.gz
```

Now consider the following MWE:

````
---
title: "Title"
# engine: knitr
execute:
  cache: true
format:
  pdf:
    header-includes:
      \usepackage{tabularray}
---

```{r}
#| label: setup
#| output: false
library(modelsummary)
mod <- lm(mpg~cyl, data=mtcars)
```

# Section 1

```{r}
#| label: tbl-reg-results
#| output: asis
modelsummary(mod)
```
````

Open with RStudio and compile in PDF two times.

The second time you will get the following error:

```
ERROR: 
compilation failed- error
Misplaced \noalign.
\toprule ->\noalign 
                    {\ifnum 0=`}\fi \@aboverulesep =\abovetopsep \global \@b...
l.248 \end
          {tblr} 

see main.log for more information.
```

One way or the other, the file is not renderable two times.

**Comment by vincentarelbundock** [comment]
This is documented here:  https://vincentarelbundock.github.io/tinytable/man/tt.html#latex-preamble

**Comment by vincentarelbundock** [comment]
Also documented here: https://modelsummary.com/man/modelsummary.html#latex-preamble

**Comment by raffaem** [comment]
Sorry, I still don't understand what is the solution.

Can you help me by detailing what is the solution to my problem?

The documentation says that I have to add the preamble manually if the  results  are not cached.

So I need a `header-includes` that somehow checks whether the results  are cached and if not adds the preamble?

Is that what I am supposed to do?

**Comment by vincentarelbundock** [comment]
Just add them to header-includes. No need to make this conditional.

**Comment by raffaem** [comment]
Oh sorry I just read the modelsummary documentation.

The tinytable documentation says:

> Note: Your document will fail to compile to PDF in Quarto if you enable caching and you use tinytable due to missing LaTeX headers. To avoid this problem, set the option #| cache: false for the chunk(s) where you use tinytable.

I think the modelsummary documentation should report that as well

(is there really no other way? Is it not possible to add the preamble even when cached?)

**Comment by vincentarelbundock** [comment]
AFAIK, there is no way for `modelsummary` to add the preamble automatically when a code chunk is cached.

**Comment by raffaem** [comment]
> Just add them to header-includes. No need to make this conditional.

It doesn't work

````
---
title: "Title"
engine: knitr
execute:
  cache: true
format:
  pdf: 
    header-includes:
      - \usepackage{tabularray}
      - \usepackage{float}
      - \usepackage{graphicx}
      - \usepackage{rotating}
      - \usepackage[normalem]{ulem}
      - \UseTblrLibrary{booktabs}
      - \UseTblrLibrary{siunitx}
      - \newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
      - \newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
      - \NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
---

```{r}
#| label: setup
#| output: false
library(modelsummary)
mod <- lm(mpg~cyl, data=mtcars)
```

# Section 1

```{r}
#| label: tbl-reg-results
#| output: asis
modelsummary(mod)
```
````

```
ERROR: 
compilation failed- error
LaTeX Error: Command \tinytableTabularrayUnderline already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.155 ...leTabularrayUnderline}[1]{\underline{#1}}
                                                   

see main.log for more information.
```
